/// Generated by `init.sh`.
/// Do not hand-edit; run the initializer again.
class LocalFallbackDefaults {
  const LocalFallbackDefaults._();

  static const String baseUrl = 'http://192.168.1.192';
  static const String homeWifiSsid = '';
  static const String homeWifiPassword = '';
  static const String sharedKey =
      'e0ef3e2f133dcad3e983aa4776452ec33cda499a5f732ae28bf47ca20a74a02d';
  static const int unlockPulseMs = 5000;
}
